### ISSUE TITLE
Protocolo HTTPS para topográfico

### ISSUE THREAD

**Issue by geraldo** [geraldo/bellamar#2]
Ahora mismo se usa el WMS del topográfico del ICGC desde la siguiente dirección: http://geoserveis.icc.cat/icc_mapesmultibase/utm/wms/service

@carlospsig, cual es el substituto correcto con el protocolo HTTPS? Debería ser uno de estos, pero funcionan en diferentes escalas: https://www.icgc.cat/Administracio-i-empresa/Serveis/Geoinformacio-en-linia-Geoserveis/WMS-Topografics

**Comment by carlospsig** [comment]
Hola @geraldo 
Aquí tienes el WMS correcto
https://www.icgc.cat/Administracio-i-empresa/Serveis/Geoinformacio-en-linia-Geoserveis/WMS-i-tessel-les-Cartografia-de-referencia/WMS-WMTS-rapids-de-cartografia-raster/WMS-rapid-de-cartografia-raster-en-coordenades-UTM
