### ISSUE TITLE
Añadir favicon

### ISSUE THREAD

**Issue by geraldo** [geraldo/bellamar#7]
@carlospsig, ¿podemos usar el ícono de la web del Aj. de Castelldefels? 

https://www.castelldefels.org/A_Comuns/_Pells/_Comu/Img/IconaAjuntament_2011.ico

**Comment by carlospsig** [comment]
Sí, justo esta mañana lo he visto y te lo quería proponer, pero se me olvidó comentártelo.
La propuesta que haces me parece muy correcta.
Gracias
